name: Ranks
version: ${project.version}
main: dev.echo.ranks.RankPlugin
api-version: 1.16
authors: [ Echo ]
description: A Rank Plugin

commands:
  rank:
    description: give players a rank!
    aliases:
      - rnk

